version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: bookstore
      
    ports:
      - "3310:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Tự động chạy script tạo database & dữ liệu mẫu
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis-cache:
    image: redis:8-alpine
    container_name: redis-cache
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  book-store-api:
    build: .
    container_name: book-store-api
    restart: always
    depends_on:
      mysql-db:
        condition: service_healthy  # Chỉ khởi động Spring Boot khi MySQL đã sẵn sàng
      redis-cache:
        condition: service_healthy  # Khởi động khi Redis đã sẵn sàng
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_URL: jdbc:mysql://mysql-db:3306/bookstore?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      REDIS_HOST: redis-cache
      REDIS_PORT: 6379

volumes:
  mysql_data: